name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - pandas
    - matplotlib
    - numpy
    - sklearn
    - ipython
    - seaborn
    - ipywidgets
    - psutil
    - toolz
    - matplotlib
    - dill
    - pandas
    - partd
    - bokeh
    - dask
